name: venv_python_3_10
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cycler==0.12.1
  - fastdtw==0.3.4
  - fonttools==4.45.0
  - joblib==1.3.2
  - kiwisolver==1.4.5
  - matplotlib==3.8.2
  - numpy==1.26.0
  - opencv==4.6.0
  - packaging==23.2
  - pandas==2.1.3
  - pillow==10.0.1
  - pyparsing==3.1.1
  - python-dateutil==2.8.2
  - pytz==2023.3.post1
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.1
  - seaborn==0.13.0
  - six==1.16.0
  - threadpoolctl==3.2.0
  - wxpython==4.1.1
