name: venv_python_3_10
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - numpy>=1.24.0
    - pandas>=2.0.0
    - matplotlib>=3.7.0
    - scipy>=1.10.0
    - scikit-learn>=1.3.0
    - opencv-python>=4.8.0
    - pyyaml>=6.0
    - pyqtgraph>=0.13.0
    - fastdtw>=0.3.4
    - seaborn>=0.12.0
    - PySide6>=6.6.0
